# leap.toml

# Define build settings if needed (adapt command/directory if necessary)
build_command = "npm run build"
publish_dir = "dist" # Make sure this matches your Vite output directory

# Define routes - this handles the SPA rewrite
[routes]
"/*" = "/index.html"